### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by life-elixir** [shlomikushchi/zipline-trader#150]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Linux
* Python Version: 3.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: pip
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
 I expected to run the algo on Linux but I got an error message
* What happened instead? 
I got the following error:
ValueError: SQLite file '/home/ubuntu/.zipline/data/alpaca_api/2020-12-07T02;06;17.365878/assets-7.sqlite' doesn't exist.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. I used a brand new enviroment but it didn’t resolve the issue.
2.
3.
...
Let me tell everyone what I did with Dan's help:
in my root folder /home/ubuntu: git clone https://github.com/shlomikushchi/zipline-trader.git
conda create -n zipline-trader_py36_v1 python=3.6
conda activate zipline-trader_py36_v1 
cd zipline-trader
pip install -e .
change the path for alpaca.yaml in alpaca_api.py to /home/ubuntu/.zipline/alpaca.yaml
add ZIPLINE_ROOT=/home/ubuntu/.zipline my ~/.bashrc file and restart or source ~/.bashrc
I got the following error
alpaca_api.py:259: UserWarning: Overwriting bundle with name 'alpaca_api'
  def api_to_bundle(interval=['1m']):
alpaca_api.py:334: UserWarning: Overwriting bundle with name 'alpaca_api'
  end_session=end_date
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 140, in _one_request
    resp.raise_for_status()
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://paper-api.alpaca.markets/v2/assets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "alpaca_api.py", line 342, in <module>
    show_progress=True,
  File "/home/ubuntu/zipline-trader/zipline/data/bundles/core.py", line 443, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "alpaca_api.py", line 284, in ingest
    metadata = metadata_df()
  File "alpaca_api.py", line 253, in metadata_df
    np.empty(len(list_assets()), dtype=metadata_dtype))
  File "alpaca_api.py", line 40, in list_assets
    ASSETS = [_.symbol for _ in CLIENT.list_assets()]
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 405, in list_assets
    resp = self.get('/assets', params)
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 156, in get
    return self._request('GET', path, data)
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 119, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/ubuntu/anaconda3/envs/zipline-trader_py36_v6/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 148, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: account not found for f3dbfcc6-839c-4de6-911e-37fcf9bdf180
## What steps have you taken to resolve this already?

...

# Anything else?
when I do the source ~/.bashrc it exits my environment

and conda activate zipline-trader_py36_v1

python alpaca_api.py returns this error:
Traceback (most recent call last):
  File "alpaca_api.py", line 16, in <module>
    from zipline.data.bundles import core as bundles
ModuleNotFoundError: No module named 'zipline'

I am surprised that it means that I never installed zipline-trader there

will you please elaborate?
...

Sincerely,
`$ whoami`

**Comment by life-elixir** [comment]
Resolved by:
in my root folder /home/ubuntu: git clone https://github.com/shlomikushchi/zipline-trader.git
conda create -n zipline-trader_py36_v1 python=3.6
conda activate zipline-trader_py36_v1
cd zipline-trader
pip install -e .
change the path for alpaca.yaml in alpaca_api.py to /home/ubuntu/.zipline/alpaca.yaml
add ZIPLINE_ROOT=/home/ubuntu/.zipline my ~/.bashrc file and restart or source ~/.bashrc
