### ISSUE TITLE
backtest example error: cannot import name 'complete_to_chordal_graph'

### ISSUE THREAD

**Issue by arisliang** [shlomikushchi/zipline-trader#178]
An error happened when copy and run the backtest example from https://zipline-trader.readthedocs.io/en/latest/backtest.html. Error details is:

>(zipline-trader) C:\src\lycn\zipline-trader-start>python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from zipline.utils.calendars import get_calendar
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\utils\run_algo.py", line 30, in <module>
    from zipline.pipeline.data import USEquityPricing
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\pipeline\__init__.py", line 8, in <module>
    from .graph import ExecutionPlan, TermGraph
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\pipeline\graph.py", line 6, in <module>
    import networkx as nx
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\__init__.py", line 61, in <module>
    import networkx.generators
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\generators\__init__.py", line 16, in <module>
    from networkx.generators.intersection import *
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\generators\intersection.py", line 5, in <module>
    from networkx.algorithms import bipartite
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\algorithms\__init__.py", line 79, in <module>
    import networkx.algorithms.tree
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\algorithms\tree\__init__.py", line 6, in <module>
    from .decomposition import *
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\networkx\algorithms\tree\decomposition.py", line 5, in <module>
    from networkx.algorithms import moral, complete_to_chordal_graph, chordal_graph_cliques
ImportError: cannot import name 'complete_to_chordal_graph'

**Comment by arisliang** [comment]
Python: 3.6
zipline-trader: 1.6.0
OS: windows 10

**Comment by arisliang** [comment]
Should be pip package issue, wasn't able to import networkx in python. Not related to zipline-trader.
