### ISSUE TITLE
config.data_backend referenced in code but not accessible from release bundle

### ISSUE THREAD

**Issue by andrewchch** [shlomikushchi/zipline-trader#179]
https://github.com/shlomikushchi/zipline-trader/blob/dbfe73d32072f0a926b1153bad636245e9a359e6/zipline/data/psql_daily_bars.py#L19

Looks like the config package has been included in the 1.60 build at the root of the package but is not available once the package is installed, so I get:

from zipline import run_algorithm
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-088d53790bc9>", line 1, in <module>
    from zipline import run_algorithm
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\utils\run_algo.py", line 24, in <module>
    from zipline.data import bundles
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\data\bundles\__init__.py", line 2, in <module>
    from . import quandl  # noqa
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\data\bundles\quandl.py", line 16, in <module>
    from . import core as bundles
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\data\bundles\core.py", line 19, in <module>
    from ..psql_daily_bars import PSQLDailyBarReader, PSQLDailyBarWriter
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366\lib\site-packages\zipline\data\psql_daily_bars.py", line 19, in <module>
    import config.data_backend
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'config'

at line 19 in psql_daily_bars.py:

import config.data_backend

**Comment by andrewchch** [comment]
Works fine in 1.5.0

**Comment by Sutyke** [comment]
To help you to debug the problem I would advice to first try:

1)  run install and run back-test examples according [video 
tutorials](https://zipline-trader.readthedocs.io/en/latest/backtest.html) (do not use pycharm).

2)  activate env, run in cmd `python` and in python run `from zipline import run_algorithm`. 

If there is still problem post error backtrace from the step 1 and step 2

I think problem is related to pycharm as env variables needs to be set inside pycharm `ZIPLINE_TRADER_CONFIG= FULL PATH TO/zipline-trader.yaml`. You can check in pycharm docs how to do it.

**Comment by shlomikushchi** [comment]
released in 1.6.0
please let me know if there are still issues
