### ISSUE TITLE
error loading data bundles without specifying custom asset list

### ISSUE THREAD

**Issue by arisliang** [shlomikushchi/zipline-trader#181]
The documentation says custom asset list is an alternative if universe is selected. But if don't put custom asset list in config, it gives key error:

>(zipline-trader) C:\zipline-trader>python zipline\data\bundles\alpaca_api.py
zipline\data\bundles\alpaca_api.py:276: UserWarning: Overwriting bundle with name 'alpaca_api'
  def api_to_bundle(interval=['1m']):
zipline\data\bundles\alpaca_api.py:354: UserWarning: Overwriting bundle with name 'alpaca_api'
  end_session=end_date
Traceback (most recent call last):
  File "zipline\data\bundles\alpaca_api.py", line 362, in <module>
    show_progress=True,
  File "c:\zipline-trader\zipline\data\bundles\core.py", line 513, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "zipline\data\bundles\alpaca_api.py", line 290, in ingest
    assets_to_sids = asset_to_sid_map(asset_db_writer.asset_finder, list_assets())
  File "zipline\data\bundles\alpaca_api.py", line 43, in list_assets
    custom_asset_list = conf.custom_asset_list
  File "c:\zipline-trader\config\bundle.py", line 47, in custom_asset_list
    return self.al["custom_asset_list"]
KeyError: 'custom_asset_list'

**Comment by shlomikushchi** [comment]
thanks. fixed: f5594eb6e3895613f8b8748850473ca2540d6ad2
