### ISSUE TITLE
Error when specifying date earlier than existing bundle

### ISSUE THREAD

**Issue by arisliang** [shlomikushchi/zipline-trader#182]
When specifying date earlier than existing bundle, it gives this error:

>(zipline-trader) C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader>python zipline\data\bundles\alpaca_api.py
zipline\data\bundles\alpaca_api.py:276: UserWarning: Overwriting bundle with name 'alpaca_api'
  def api_to_bundle(interval=['1m']):
zipline\data\bundles\alpaca_api.py:354: UserWarning: Overwriting bundle with name 'alpaca_api'
  end_session=end_date

>Traceback (most recent call last):
  File "zipline\data\bundles\alpaca_api.py", line 362, in <module>
    show_progress=True,
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\bundles\core.py", line 513, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "zipline\data\bundles\alpaca_api.py", line 306, in ingest
    daily_bar_writer.write(daily_data_generator(), assets=assets_to_sids.values(), show_progress=True)
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 617, in write
    return self._write_internal(it, assets)
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 665, in _write_internal
    for asset_id, table in iterator:
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 658, in iterator
    for asset_id, table in iterator:
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\click\_termui_impl.py", line 318, in generator
    for rv in self.iter:
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 609, in <genexpr>
    for sid, df in data
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 716, in _write_to_postgres
    result = self._format_df_columns_and_index(data, sid)
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 731, in _write_to_postgres
    result = self._validate_data_consistency_on_edges(sid, data, edge_days, invalid_data_behavior)
  File "c:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 751, in _validate_data_consistency_on_edges
    backward_gap = len(self._calendar.sessions_in_range(before_slice.index[-1], first_day))
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\trading_calendars\trading_calendar.py", line 702, in sessions_in_range
    end_session_label
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\pandas\core\indexes\datetimes.py", line 815, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\pandas\core\indexes\base.py", line 4713, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\pandas\core\indexes\base.py", line 4922, in slice_locs
    raise ValueError("Both dates must have the same UTC offset")
ValueError: Both dates must have the same UTC offset

**Comment by shlomikushchi** [comment]
Hi, 
you can't specify dates before your bundle

**Comment by vaa1234** [comment]
I am getting exactly the same error without specifying dates. I just run alpha_vantage_api.py file.
