### ISSUE TITLE
Facing Pandas Error when running algos with minute level data

### ISSUE THREAD

**Issue by sauravkpaul** [shlomikushchi/zipline-trader#184]
Starting zipline 1.6.0, algos with minute level data bundles and data fequency=minute is not working. Getting the below backtrace. 
`
Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 471, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
TypeError: an integer is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 473, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 479, in pandas._libs.index.DatetimeEngine._date_check_type
KeyError: 'NaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 471, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
TypeError: an integer is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 715, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 473, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 479, in pandas._libs.index.DatetimeEngine._date_check_type
KeyError: 'NaT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 463, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: -9223372036854775808

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 465, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: NaT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 463, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: -9223372036854775808

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 728, in get_loc
    return Index.get_loc(self, stamp, method, tolerance)
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 433, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 465, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: NaT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "my_orb_attempt.py", line 248, in <module>
    data_frequency='minute'
  File "/Users/saurav/PyAlgo/new_zipline/zipline-trader/zipline/utils/run_algo.py", line 489, in run_algorithm
    execution_id=execution_id
  File "/Users/saurav/PyAlgo/new_zipline/zipline-trader/zipline/utils/run_algo.py", line 207, in _run
    adjustment_reader=bundle_data.adjustment_reader,
  File "/Users/saurav/PyAlgo/new_zipline/zipline-trader/zipline/data/data_portal.py", line 291, in __init__
    if self._first_trading_day is not None else (None, None)
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/trading_calendars/trading_calendar.py", line 844, in open_and_close_for_session
    self.session_open(session_label),
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/trading_calendars/trading_calendar.py", line 871, in session_open
    'market_open'
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexing.py", line 2178, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/frame.py", line 2919, in _get_value
    index = self.index.get_loc(index)
  File "/usr/local/anaconda3/envs/new_zipline/lib/python3.6/site-packages/pandas/core/indexes/datetimes.py", line 730, in get_loc
    raise KeyError(key)
KeyError: 'NaT'
`

The same algorithm file with same data bundle works fine on another environment where I have zipline 1.5.0 installed. Possibly pandas 1.1.5 is causing some issue but I am not able to root cause it.

**Comment by shlomikushchi** [comment]
hi, minute data is not currently supported

**Comment by sauravkpaul** [comment]
Ok. Closing
