### ISSUE TITLE
Problem with h5py and zipline-trader 1.6

### ISSUE THREAD

**Issue by andrewchch** [shlomikushchi/zipline-trader#185]
Env: Windows 10, Python 3.6.6, HDF5 installed

I get the same issue with current head, 1.6.0 and 1.5.0 releases. 

I've tried many different ways to resolve this but I just can't seem to get past this problem:

(venv_366_new) C:\Users\Andrew\PycharmProjects\investing\zipline-trader>zipline
Traceback (most recent call last):
  File "C:\Users\Andrew\PycharmProjects\investing\venv_366_new\Scripts\zipline-script.py", line 33, in <module>
    sys.exit(load_entry_point('zipline-trader', 'console_scripts', 'zipline')())
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\pkg_resources\__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\pkg_resources\__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
    return self.resolve()
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\utils\run_algo.py", line 24, in <module>
    from zipline.data import bundles
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\data\bundles\__init__.py", line 2, in <module>
    from . import quandl  # noqa
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\data\bundles\quandl.py", line 16, in <module>
    from . import core as bundles
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\data\bundles\core.py", line 15, in <module>
    from ..minute_bars import (
  File "c:\users\andrew\pycharmprojects\investing\zipline-trader\zipline\data\minute_bars.py", line 24, in <module>
    import h5py
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\h5py\__init__.py", line 34, in <module>
    from . import version
  File "c:\users\andrew\pycharmprojects\investing\venv_366_new\lib\site-packages\h5py\version.py", line 17, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: The specified procedure could not be found.

I've followed all the install instructions and still get this. What's odd is that if I do "import h5py" or "import zipline" in the same virtual env it works. 

Any ideas???

**Comment by yinjin1314** [comment]
i think you need to make sure the h5py version=2.10.0 ,and hdf5 version =1.10.5

**Comment by andrewchch** [comment]
That worked !!! Thank you so much :-)
