### ISSUE TITLE
alpaca_api load data error from 2005-02-01 to 2004-02-01

### ISSUE THREAD

**Issue by arisliang** [shlomikushchi/zipline-trader#188]
I try to load historical data from alpaca for custom_asset_list: AAPL, TSLA, GOOG, and changed time period to:

>end_date = pd.Timestamp('2005-02-01 0:00', tz='utc')
start_date = end_date - timedelta(days=365)

It gives `IndexError: index 0 is out of bounds for axis 0 with size 0` error:

>C:\Users\arisl\anaconda3\envs\zipline-trader\python.exe C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py
C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py:276: UserWarning: Overwriting bundle with name 'alpaca_api'
  def api_to_bundle(interval=['1m']):
C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py:355: UserWarning: Overwriting bundle with name 'alpaca_api'
  end_session=end_date
Traceback (most recent call last):
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 363, in <module>
    show_progress=True,
  File "C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\bundles\core.py", line 513, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 306, in ingest
    daily_bar_writer.write(daily_data_generator(), assets=assets_to_sids.values(), show_progress=True)
  File "C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 617, in write
    return self._write_internal(it, assets)
  File "C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 665, in _write_internal
    for asset_id, table in iterator:
  File "C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 658, in iterator
    for asset_id, table in iterator:
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\click\_termui_impl.py", line 315, in generator
    for rv in self.iter:
  File "C:\src\lycn\conda-environments\zipline-trader\src\zipline-trader\zipline\data\psql_daily_bars.py", line 608, in <genexpr>
    (sid, self._write_to_postgres(sid, df, invalid_data_behavior))
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 299, in <genexpr>
    return (sid_df for (sid_df, *metadata.iloc[sid_df[0]]) in df_generator(interval='1d',
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 238, in df_generator
    df: pd.DataFrame = get_aggs_from_alpaca(partial, start, end, 'day' if interval == '1d' else 'minute', 1)
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 203, in get_aggs_from_alpaca
    response = _iterate_api_calls()
  File "C:/src/lycn/conda-environments/zipline-trader/src/zipline-trader/zipline/data/bundles/alpaca_api.py", line 128, in _iterate_api_calls
    if response.index[0] <= (pytz.timezone(NY).localize(
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\pandas\core\indexes\extension.py", line 209, in __getitem__
    result = self._data[key]
  File "C:\Users\arisl\anaconda3\envs\zipline-trader\lib\site-packages\pandas\core\arrays\datetimelike.py", line 514, in __getitem__
    val = getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by shlomikushchi** [comment]
Hi, 
that's a data provider issue. check what ranges they provide. (I think 5 years)
you could also try alpha-vantage. their free tier should cover that.

**Comment by shlomikushchi** [comment]
no, both dates must be valid trading dates. you could use the trading_calenders package to check that
